[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "workspace-test"
version = "0.1.0"
description = "Test"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = "MIT"
